version: '2.0'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: annuaire-backend
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/html/
    depends_on:
      - db
    networks:
      - proxy_https_default
    env_file:
      - .env
 
  #Nginx Service
  webserver:
    build: ./nginx
    ports:
      - 1300:80
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=dev.harouna@gmail.com
    container_name: webserver
    restart: unless-stopped
    tty: true
    networks:
      - proxy_https_default
    depends_on:
      - db
    env_file:
      - .env
  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3360"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
    networks:
      - proxy_https_default
    env_file:
      - .env
 
#Docker Networks
networks:
  proxy_https_default:
    external: true
