version: '3.7'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: annuaire-backend
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/html/
    depends_on:
      - db
    links:
      - db
    networks:
      - proxy_https_default
    volumes:
      - app:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    env_file:
      - .env
 
  #Nginx Service
  webserver:
    build: ./nginx
    ports:
      - 1300:80
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=dev.harouna@gmail.com
    container_name: webserver
    restart: unless-stopped
    tty: true
    networks:
      - proxy_https_default
    depends_on:
      - db
    volumes:
      - app:/var/www/html/
    env_file:
      - .env
  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3360"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
    networks:
      - proxy_https_default
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db2:/var/lib/mysql4
    env_file:
      - .env
 
volumes:
  app:
  db2:
#Docker Networks
networks:
  proxy_https_default:
    external: true