name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            rm -rf annuaire-backend
            git clone git@github.com:babaata/annuaire-backend.git
            cp -r .env annuaire-backend/ && cd annuaire-backend
            docker-compose up -d --build --force-recreate
            docker-compose exec app php artisan key:generate
            docker-compose exec app php artisan config:cache
            docker-compose exec app php artisan migrate
            echo 'Deployment successful'
